name: Update Docs

on:
  push:
    branches:
      - master
    paths:
      - "docs/**"

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install VuePress
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: --cwd docs add -D vuepress

      - name: Print yarn bin
        run: echo "$(ls $(yarn bin) | xargs)"
        working-directory: ./docs

      - name: Build
        run: $(yarn bin)/vuepress build
        working-directory: ./docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./docs/.vuepress/dist
        with:
          emptyCommits: false
